export const NavLinks = [
  {
    to: "/",
    title: "Главный",
  },
  {
    to: "/about",
    title: "O нас",
  },
  {
    to: "/menu/sweets",
    title: "Меню",
  },
  {
    to: "/features",
    title: "Наши ценности",
  },
  {
    to: "/location",
    title: "Локации",
  },
  {
    to: "/carrier",
    title: "Карьера",
  },
  {
    to: "/store",
    title: "Safia Store",
  },
];
export const NewProducts = [
  {
    id: 1,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681738112.",
    title: "Джульетта рулет кусок",
    body: "Ягодный бисквит прослойка из малинового ( клубничного) джема",
    price: 27,
    quantity: 1,
  },
  {
    id: 2,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681738020.",
    title: "малиновый тарт",
    body: "Песочное ореховое тесто начинкой из шоколадного ганаша и взбитых сливок.",
    price: 25,
    quantity: 1,
  },
  {
    id: 3,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1682508637.",
    title: "Сан-Себастьян чизкейк",
    body: "Запеченная корочка творожно-сливочный крем",
    price: 26,
    quantity: 1,
  },
  {
    id: 4,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681738186.",
    title: "Сникерс рулет кусок",
    body: "Шоколадный бисквит шоколадный сливочный крем грецкие орехи ириской",
    price: 27,
    quantity: 1,
  },
  {
    id: 5,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681737651.",
    title: "Тропический тарт",
    body: "Кокосовый бисквит, кремами маракуя и кокоса. Оформлен шоколадным декором.",
    price: 24,
    quantity: 1,
  },
  {
    id: 6,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681738057.",
    title: "Фисташково вишневый тарт",
    body: "Фисташковый бисквит, вишневая начинка и фисташковый крем",
    price: 28,
    quantity: 1,
  },
];
export const TopTarts = [
  {
    id: 1,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1669992159.png",
    title: "Блэк форест тарталетка",
    body: "Ягодный бисквит прослойка из малинового ( клубничного) джема",
    price: 20,
    quantity: 1,
  },
  {
    id: 2,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672828185.png",
    title: "Вишенка тарт",
    body: "Песочное ореховое тесто начинкой из шоколадного ганаша и взбитых сливок.",
    price: 85,
    quantity: 1,
  },
  {
    id: 3,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054082.png",
    title: "Фисташковый пирог",
    body: "Запеченная корочка творожно-сливочный крем",
    price: 140,
    quantity: 1,
  },
  {
    id: 4,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671014979.png",
    title: "Черный принц торт круглый",
    body: "Шоколадный бисквит шоколадный сливочный крем грецкие орехи ириской",
    price: 230,
    quantity: 1,
  },
];
export const Tortlar = [
  {
    img: "https://safiabakery.uz/uploads/products/171_1671024360.png",
    name: "Джульетта",
  },
  {
    img: "https://safiabakery.uz/uploads/products/171_1678877392.png",
    name: "Мороженка торт",
  },
  {
    img: "https://safiabakery.uz/uploads/products/171_1671271062.png",
    name: "Панчо торт",
  },
  {
    img: "https://safiabakery.uz/uploads/products/171_1683100948.",
    name: "Сафия оформленный",
  },
  {
    img: "https://safiabakery.uz/uploads/products/171_1671252382.png",
    name: "Фруктовый торт круглый",
  },
  {
    img: "https://safiabakery.uz/uploads/products/171_1671014979.png",
    name: "Черный принц торт круглый",
  },
];
export const Feat = [
  {
    icon: "https://careers.safiabakery.uz/img/learning-ic.svg",
    title: "Окружающая среда",
    body: "Safia заботиться o будущем",
  },
  {
    icon: "https://careers.safiabakery.uz/img/free-food-ic.svg",
    title: "Семья",
    body: "Сохраняя семейные ценности делаем жизнь людей праздником",
  },
  {
    icon: "https://careers.safiabakery.uz/img/system-adoptation-ic.svg",
    title: "Инклюзия",
    body: "Равные возможности для всех",
  },
];
export const News = [
  {
    id: 1,
    img: "./img/p1.jpg",
    title: "Ароматное лакомство!",
    body: "неотъемлемый десерт в теплом семейном чаепитии.",
  },
  {
    id: 2,
    img: "./img/p2.jpg",
    title: "Анонс!",
    body: "A еще, вы найдете сюрприз для маленьких читателей Safia Magazine.",
  },
  {
    id: 3,
    img: "./img/p3.jpg",
    title: "Начнем новый учебный год вместе c Safia!",
    body: "Пусть ваши занятия будут интересными и насыщенными.",
  },
  {
    id: 4,
    img: "./img/p4.jpg",
    title: "Новинка!",
    body: "Любимое печенье в мини-упаковке: «Кофейное» ,«Ореховые мини-кольца»",
  },
  {
    id: 5,
    img: "./img/p5.jpg",
    title: "Safia открывает второй филиал в Намангане!",
    body: "Уже c 26 августа жители города. Наманган, мкр. 5A, ул. Галаба, ресторан Eiffel ",
  },
  {
    id: 6,
    img: "./img/p6.jpg",
    title: "Экзотический чизкейк.",
    body: "Этот чизкейк co вкусом лета, абсолютный фаворит среди чизкейков.",
  },
];
export const About = [
  {
    id: 1,
    img: "https://safiabakery.uz/uploads/pages/page_1672066470.jpg",
    title: "НАША ИСТОРИЯ",
    link: "/about/history",
    body: "История создания популярногопроизводителя сладостей и выпечки, завоевавшего славу, благодаря мечте создать кондитерскую культуру в Узбекистане, и большой любви к общему, семейному делу.",
  },
  {
    id: 2,
    img: "https://safiabakery.uz/uploads/pages/page_1672055055.jpg",
    title: "НАШИ ДОСТИЖЕНИЯ",
    link: "/about/achievments",
    body: "Результат работы нашего коллектива отражает решения и стремления нашей команды в целом. B свою очередь, наши достижения являются стимулом для дальнейшего развития нашей работы.",
  },
  {
    id: 3,
    img: "https://safiabakery.uz/uploads/pages/page_1671111750.png",
    title: "SAFIA STORE",
    link: "/menu/store",
    body: "C целью быть еще ближе к нашимгостям мы запустили лимитированнуюколлекцию на нашей странице Safia Store. B нашей коллекции мы отразиличастичку индивидуальности длякаждого, чтобы вы стали частью нашейбольшой и дружной семьи!",
  },
];
export const Cennos = [
  {
    id: 1,
    img: "https://safiabakery.uz/uploads/pages/page_1679316092.png",
    title: "ОКРУЖАЮЩАЯ СРЕДА",
    body: "Нашей безусловной целью является - сохранить для будущего поколения стабильное и чистое будущее поддерживая экологию здесь и сейчас.",
  },
  {
    id: 2,
    img: "https://safiabakery.uz/uploads/pages/page_1673269026.png",
    title: "СЕМЬЯ",
    body: "Мы любим своё дело! Сохраняя семейные ценности, мы развиваем кондитерское искусство. Мы создаем для каждого человека и семьи праздник! Мы любим наших гостей и гарантируем продукцию из натуральных ингредиентов высшего качества.",
  },
  {
    id: 3,
    img: "https://safiabakery.uz/uploads/pages/page_1672128875.png",
    title: "ИНКЛЮЗИЯ",
    body: "Предоставление рабочих мест и условий c заботой o каждом!",
  },
];
export const Punto = [
  {
    img: "https://careers.safiabakery.uz/img/gosts.jpg",
    title: "ГОСТИ",
    body: "Мы дорожим доверием гостей всех поколений",
  },
  {
    img: "https://careers.safiabakery.uz/img/products.jpg",
    title: "ПРОДУКТ",
    body: "У нас всегда как дома, на все случаи жизни",
  },
  {
    img: "https://careers.safiabakery.uz/img/family.jpg",
    title: "СЕМЬЯ",
    body: "Мы живем, как одна большая семья и ценим каждого сотрудника",
  },
  {
    img: "https://careers.safiabakery.uz/img/development.jpg",
    title: "РАЗВИТИЕ",
    body: "Сохраняя вкусы, сохраняем традиции Safia",
  },
];
export const Icons = [
  {
    img: "https://careers.safiabakery.uz/img/comfortable-schadule-ic.svg",
    title: "Удобный график",
  },
  {
    img: "https://careers.safiabakery.uz/img/work-with-study-ic.svg",
    title: "Возможность совмещать работу с учёбой",
  },
  {
    img: "https://careers.safiabakery.uz/img/near-to-home-ic.svg",
    title: "Локация рядом с домом",
  },
  {
    img: "https://careers.safiabakery.uz/img/rocket-ic.svg",
    title: "Постоянный рост заработной платы",
  },
  {
    img: "https://careers.safiabakery.uz/img/system-adoptation-ic.svg",
    title: "Продуманная система адаптации",
  },
  {
    img: "https://careers.safiabakery.uz/img/free-medicine-ic.svg",
    title: "Бесплатный медицинский осмотр",
  },
  {
    img: "https://careers.safiabakery.uz/img/learning-ic.svg",
    title: "Обучение и развитие",
  },
  {
    img: "https://careers.safiabakery.uz/img/free-food-ic.svg",
    title: "Бесплатное питание",
  },
  {
    img: "https://careers.safiabakery.uz/img/comfortable-schadule-ic.svg",
    title: "Карьерный рост",
  },
  {
    img: "https://careers.safiabakery.uz/img/interesting-projects-ic.svg",
    title: "Интересные проекты для развития",
  },
];
export const Jobs = [
  {
    title: "ОПЕРАТОР КОНТАКТ-ЦЕНТРА",
    ex: "Без опыта",
    job: "Приём и обработка входящих звонков.",
    needs: "Знание узбекского и русского языков.",
    workTime: "Время работы:c 8:00 до 16:00, 16:00 до 23:00.",
    type: "ОПЕРАТОР",
  },
  {
    title: "ФИНАНСИСТ",
    ex: "Требуемый опыт работы: 3–6 лет",
    job: "- грамотное управление финансовыми потоками компании;",
    needs: " высшее экономическая и финансовая образование;",
    workTime: "- график работы 6/1 с 09:00 до 18:00;",
    type: "ФИНАНСИСТ",
  },
  {
    title: "КАССИР В КОНДИТЕРСКИЙ ДОМ САФИЯ (ЧИЛАНЗАРСКИЙ Р-Н)",
    ex: "Требуемый опыт работы: 1-3 лет",
    job: "Производить расчетно-кассовые операции в программе IIKO;",
    needs: "Имеет опыт работы на аналогичной должности;",
    workTime: "- График работы: 6/1 с плавающими выходными, с 08:00 до 16:00;",
    type: "КАССИР",
  },
  {
    title: "КОНДИТЕР",
    ex: "Без опыта",
    job: "Изготовление кондитерских изделий на определённых этапах",
    needs: `
    -умение работать в команде;
    -опрятный внешний вид;
    -стрессоустойчивость.
    `,
    workTime: `
    - график работы 6/1, с плавающим выходным;
    - Время работы:
    1-смена- 08:00-17:00
    2-смена- 17:00-02:00
    `,
    type: "КОНДИТЕР",
  },
];
export const Storejon = [
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/no-photo.jpg",
    name: "Пакет",
    soni: "В комплекте 1 шт",
    price: 50,
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/27_1661334995.jpg",
    name: "Подарочный пакет",
    soni: "В комплекте 1 шт",
    price: 20,
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/27_1665680252.jpg",
    name: "Тарелки праздничные",
    soni: "В комплекте 10 шт",
    price: 10,
  },
];
export const Menubir = [
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687197799.",
    title: "круглые торты",
    type: "круглые",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1685082141.",
    title: "большие торты",
    type: "большие",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690794297.png",
    title: "премиум коллекция тортов",
    type: "премиум",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672297405.png",
    title: "мини-торты",
    type: "мини",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687346430.",
    title: "большие пироги",
    type: "бигпироги",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672297354.png",
    title: "круглые пироги",
    type: "кругпироги",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1685082274.",
    title: "эклеры",
    type: "эклеры",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672832040.png",
    title: "тарталетки",
    type: "тарталетки",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672828379.png",
    title: "макаронсы",
    type: "макаронсы",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1688018766.png",
    title: "печенья",
    type: "печенья",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1675248839.png",
    title: "сдоба",
    type: "сдоба",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1691475539.",
    title: "кексы",
    type: "кексы",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672297730.png",
    title: "чак - чак",
    type: "чак",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1675249013.png",
    title: "слоеная выпечка",
    type: "слоеная",
    link: "*",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1675249080.png",
    title: "мясная и несладкая выпечка",
    type: "мясная",
    link: "*",
  },
];
export const Menuikki = [
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672297770.png",
    title: "пп торты",
    type: "ппторты",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672917407.png",
    title: "пп пирожные",
    type: "пппирожные",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1672917423.png",
    title: "пп печенья",
    type: "пппеченья",
    link: "*",
  },
];
export const Menuuch = [
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1677590566.jpg",
    title: "свежевыжатые соки",
    type: "cоки",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1677736054.jpg",
    title: "смузи",
    type: "смузи",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1678091069.jpg",
    title: "милкшейки",
    type: "милкшейки",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1678091089.jpg",
    title: "фраппе",
    type: "фраппе",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1678091035.jpg",
    title: "лимонады",
    type: "лимонады",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1677595033.jpg",
    title: "напитки",
    type: "напитки",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1678091108.jpg",
    title: "кофе",
    type: "кофе",
    link: "/menu/product",
  },
  {
    img: "https://safiabakery.uz/uploads/products/thumbs/g_1677735953.jpg",
    title: "авторские чаи",
    type: "чаи",
    link: "/menu/product",
  },
];
export const AllProducts = [
  {
    id: 1,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024084.png",
    title: "адмирал торт круглый",
    body: "торт состоит из макового, орехового и шоколадного классического бисквита,",
    quantity: 1,
    price: 220,
    type: "круглые",
  },
  {
    id: 2,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672059719.png",
    title: "верона стандартный торт",
    body: "торт верона состоит из белого бисквита в сочетании апельсиновым",
    quantity: 1,
    price: 170,
    type: "круглые",
  },
  {
    id: 3,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672828185.png",
    title: "вишенка тарт",
    body: "песочное тесто с классическим ганашом и свежей вишней. торт",
    quantity: 1,
    price: 85,
    type: "круглые",
  },
  {
    id: 4,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024360.png",
    title: "джульетта",
    body: "дорт джульетта состоит из классического бисквита, пропитанного",
    quantity: 1,
    price: 210,
    type: "круглые",
  },
  {
    id: 5,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672062916.png",
    title: "ириска торт",
    body: "торт ириска состоит из орехового карамельного бисквита в сочетании,",
    quantity: 1,
    price: 230,
    type: "круглые",
  },
  {
    id: 6,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024147.png",
    title: "киевский бантик",
    body: "тонкие слои классического бисквита, прослойками ганаша на белом шоколаде",
    quantity: 1,
    price: 280,
    type: "круглые",
  },
  {
    id: 7,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024267.png",
    title: "киевский оформленный торт",
    body: "торт киевский оформленный состоит из трех слоёв цветной меренге и двух",
    quantity: 1,
    price: 330,
    type: "круглые",
  },
  {
    id: 8,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690794176.png",
    title: "киевский рожок мини",
    body: "тонкие слои классического бисквита, прослойками ганаша на белом шоколаде",
    quantity: 1,
    price: 250,
    type: "круглые",
  },
  {
    id: 9,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024311.png",
    title: "киевский розовый торт",
    body: "киевский розовый торт состоит из тонких слоев классического бисквита,",
    quantity: 1,
    price: 290,
    type: "круглые",
  },
  {
    id: 10,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690794231.png",
    title: "марвел торт",
    body: "торт марвел состоит из шести слоев цветных бисквитов, в сочетании с",
    quantity: 1,
    price: 300,
    type: "круглые",
  },
  {
    id: 11,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687197526.jpg",
    title: "меренговый рулет большой",
    body: "меренговый рулет состоит из хрустящей нежной меренги, взбитых",
    quantity: 1,
    price: 180,
    type: "круглые",
  },
  {
    id: 12,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671271028.png",
    title: "микс",
    body: "микс торт состоит из классического белого и шоколадного бисквита,",
    quantity: 1,
    price: 200,
    type: "круглые",
  },
  {
    id: 13,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671024658.png",
    title: "мишель торт",
    body: "мишель торт состоит из классического бисквита, слой из медовой песочки,",
    quantity: 1,
    price: 140,
    type: "круглые",
  },
  {
    id: 14,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1678877392.png",
    title: "мороженка торт",
    body: "торт мороженка состоит и классического бисквита, в сочетании со",
    quantity: 1,
    price: 260,
    type: "круглые",
  },
  {
    id: 15,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671271062.png",
    title: "панчо торт",
    body: "торт панчо состоит из белого и шоколадного бисквита нарезанных",
    quantity: 1,
    price: 190,
    type: "круглые",
  },
  {
    id: 16,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671271130.png",
    title: "прага",
    body: "прага торт состоит из тонких шоколадных медовых коржей, в",
    quantity: 1,
    price: 160,
    type: "круглые",
  },
  {
    id: 17,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1694005216.",
    title: "птичка торт",
    body: "нежная песочная основа и классическое воздушное птичье",
    quantity: 1,
    price: 160,
    type: "круглые",
  },
  {
    id: 18,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671025231.png",
    title: "радуга торт круглый",
    body: "торт радуга состоит из 5-ти цветных бисквитов и 4-х фруктовых кремов:",
    quantity: 1,
    price: 260,
    type: "круглые",
  },
  {
    id: 19,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671253035.png",
    title: "рафаелло торт",
    body: "классический бисквит, пропитанный молочным сиропом, с прослойкой из",
    quantity: 1,
    price: 320,
    type: "круглые",
  },
  {
    id: 20,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1678877572.png",
    title: "сафия торт круглый",
    body: "торт сафия оформленный бежевый состоит и классического бисквита, в",
    quantity: 1,
    price: 250,
    type: "круглые",
  },
  {
    id: 21,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671271028.png",
    title: "сафия тортзефир мини офор",
    body: "фисташковый меренговый рулет состоит из хрустящей нежной меренги с",
    quantity: 1,
    price: 390,
    type: "круглые",
  },
  {
    id: 22,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672059420.png",
    title: "сказка рулет new",
    body: "рулет состоит из классического бисквита, пропитанного сахарным",
    quantity: 1,
    price: 140,
    type: "круглые",
  },
  {
    id: 23,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690796679.png",
    title: "сникерс торт круглый",
    body: "классический бисквит, пропитанный молочным сиропом, с прослойкой из",
    quantity: 1,
    price: 220,
    type: "круглые",
  },
  {
    id: 24,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693220292.png",
    title: "фисташковый меренговый рулет",
    body: "фисташковый меренговый рулет состоит из хрустящей нежной меренги с",
    quantity: 1,
    price: 200,
    type: "круглые",
  },
  {
    id: 25,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671252382.png",
    title: "фруктовый торт круглый",
    body: "тонкие слои классического бисквита. пропитанный сахарным сиропом.",
    quantity: 1,
    price: 220,
    type: "круглые",
  },
  {
    id: 26,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671014979.png",
    title: "черный принц торт круглый",
    body: "тонкие песочные шоколадные коржи с шоколадным сливочным кремом и",
    quantity: 1,
    price: 230,
    type: "круглые",
  },
  {
    id: 27,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672120581.png",
    title: "шоколадно - малиновый торт круглый",
    body: "песочные коржи, сливочный крем и малиновое конфи. украшен шоколадной",
    quantity: 1,
    price: 230,
    type: "круглые",
  },
  {
    id: 28,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671271233.png",
    title: "шоколадно-банановый круглый торт",
    body: "шоколадный бисквит с кофейной пропиткой, трюфельным шоколадным",
    quantity: 1,
    price: 240,
    type: "круглые",
  },
  {
    id: 29,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687254360.",
    title: "ягодно - творожный торт new",
    body: "классический бисквит в сочетании с нежной меренгой, ягодным конфи и",
    quantity: 1,
    price: 230,
    type: "круглые",
  },
  {
    id: 30,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693203863.png",
    title: "афганка new",
    body: "песочные коржи, меренга, масляный крем с добавлением вареной сгущенки",
    quantity: 1,
    price: 250,
    type: "большие",
  },
  {
    id: 31,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693203748.png",
    title: "дари торт",
    body: "тонкие слои классического бисквита в сочетании с творожно-сливочным",
    quantity: 1,
    price: 240,
    type: "большие",
  },
  {
    id: 32,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671012000.png",
    title: "итальяно торт",
    body: "ореховый бисквит 'cальма' со сливочным кремом и начинкой из",
    quantity: 1,
    price: 240,
    type: "большие",
  },
  {
    id: 33,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690793979.png",
    title: "карамельный медовый прямоугольный торт",
    body: "тонкие слои песочного теста с хрустящим безе, масляным кремом со",
    quantity: 1,
    price: 290,
    type: "большие",
  },
  {
    id: 34,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693203940.png",
    title: "лимонный торт",
    body: "тонкие слои песочного теста с хрустящим безе, масляным кремом со",
    quantity: 1,
    price: 250,
    type: "большие",
  },
  {
    id: 35,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671272620.png",
    title: "малинка торт",
    body: "классический бисквит с малиново-сливочным и бананово-сливочным",
    quantity: 1,
    price: 280,
    type: "большие",
  },
  {
    id: 36,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693204074.png",
    title: "маркиза торт",
    body: "песочные коржи, меренга, масляный крем с добавлением вареной сгущенки.",
    quantity: 1,
    price: 230,
    type: "большие",
  },
  {
    id: 37,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1694004604.png",
    title: "милано торт",
    body: "тонкие шоколадно-ореховые бисквиты с шоколадным сливочным кремом и",
    quantity: 1,
    price: 250,
    type: "большие",
  },
  {
    id: 38,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672060532.png",
    title: "наполеон торт.",
    body: "тонкие слои песочно-слоеного теста с масляным кремом со сгущенкой.",
    quantity: 1,
    price: 280,
    type: "большие",
  },
  {
    id: 39,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690794040.png",
    title: "ореховый медовый new торт",
    body: "5 тонких медовых коржей с ореховой прослойкой, сливочным - сметанным",
    quantity: 1,
    price: 290,
    type: "большие",
  },
  {
    id: 40,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672060629.png",
    title: "радуга прямоугольный мини - торт",
    body: "торт состоит из 5-ти цветных бисквитов и 4-х фруктовых кремов: вишневого,",
    quantity: 1,
    price: 280,
    type: "большие",
  },
  {
    id: 41,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1669471301.png",
    title: "саксония торт",
    body: "воздушный шоколадно - кексовый бисквит с шоколадно-сливочным",
    quantity: 1,
    price: 240,
    type: "большие",
  },
  {
    id: 42,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671012238.png",
    title: "сафия прямоугольный мини - торт",
    body: "классический бисквит с вишневым кремом с вишней, банановым кремом с",
    quantity: 1,
    price: 330,
    type: "большие",
  },
  {
    id: 43,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693204615.png",
    title: "сникерс new прямоугольный",
    body: "состоит из шоколадного бисквита, пропитанного шоколадной пропиткой. в",
    quantity: 1,
    price: 350,
    type: "большие",
  },
  {
    id: 44,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671270546.png",
    title: "творожно-бисквитный торт",
    body: "классический бисквит, пропитанный сахарным сиропом с творожно-",
    quantity: 1,
    price: 250,
    type: "большие",
  },
  {
    id: 45,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672060306.png",
    title: "три шоколада торт",
    body: "бисквит шоколадный в сочетание с темным, молочным и белым шоколадным",
    quantity: 1,
    price: 380,
    type: "большие",
  },
  {
    id: 46,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693204913.png",
    title: "фруктовый new торт прямоугольный",
    body: "фруктовый new торт состоит из тонких слоев масляного бисквита. в сочетании",
    quantity: 1,
    price: 320,
    type: "большие",
  },
  {
    id: 47,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693205114.png",
    title: "фруктовый торт прямоугольный",
    body: "тонкие слои бисквита 'сальма', со сливочно-банановым и сливочно",
    quantity: 1,
    price: 280,
    type: "большие",
  },
  {
    id: 48,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693205617.png",
    title: "шоколадно - банановый торт прямоугольный",
    body: "шоколадный бисквит с кофейной пропиткой, трюфельным кремом,",
    quantity: 1,
    price: 290,
    type: "большие",
  },
  {
    id: 49,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693206141.png",
    title: "шоколадно - малиновый торт прямоугольный",
    body: "тонкие песочные коржи со сливочным кремом, начинка малиновое конфи. торт",
    quantity: 1,
    price: 320,
    type: "большие",
  },
  {
    id: 50,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1669988133.png",
    title: "шоколадно- банановый мини - торт зеркальный",
    body: "шоколадно-банановый зеркальный мини - торт. шоколадный шифоновый",
    quantity: 1,
    price: 320,
    type: "большие",
  },
  {
    id: 51,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693205782.png",
    title: "якобс торт",
    body: "тонкие кофейные бисквиты с кофейно-сливочным кремом и шоколадной",
    quantity: 1,
    price: 270,
    type: "большие",
  },
  {
    id: 52,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693203648.png",
    title: "черный принц торт прямоугольный",
    body: "тонкие песочные шоколадные коржи со сливочным шоколадным кремом на и",
    quantity: 1,
    price: 290,
    type: "большие",
  },
  {
    id: 53,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690628189.png",
    title: "берри кейк оформленный",
    body: "берри кейк торт круглый торт со фруктовым вкусом начинка торта",
    quantity: 1,
    price: 300,
    type: "премиум",
  },
  {
    id: 54,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671011749.png",
    title: "тирамису торт",
    body: "тирамису торт состоит из классического бисквита с кофейной",
    quantity: 1,
    price: 280,
    type: "премиум",
  },
  {
    id: 55,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671011808.png",
    title: "роше торт",
    body: "торт состоит из кофейно - бананового бисквита, в сочетании с ванильным,",
    quantity: 1,
    price: 320,
    type: "премиум",
  },
  {
    id: 56,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671011113.png",
    title: "шоколадно - фисташковый торт с клубникой",
    body: "торт состоит из нежного шоколадного бисквита, пропитанным малиновым",
    quantity: 1,
    price: 290,
    type: "премиум",
  },
  {
    id: 57,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1671011490.png",
    title: "шоколадный 100% торт",
    body: "шоколадный бисквит, шоколадный штрейзель, лёгкий шоколадное кремё,",
    quantity: 1,
    price: 290,
    type: "премиум",
  },
  {
    id: 58,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672062175.png",
    title: "бенто мини - торт",
    body: "бенто - торт необходимо заказывать заранее, за 3-4 дня. рассчитан на 2-х",
    quantity: 1,
    price: 130,
    type: "мини",
  },
  {
    id: 59,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053392.png",
    title: "медовый milk slice мини - торт",
    body: "шоколадные медовые коржи, сливочный сметанный крем, шоколадная",
    quantity: 1,
    price: 140,
    type: "мини",
  },
  {
    id: 60,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677573577.png",
    title: "мини - торт «берри кейк»",
    body: "спонч бисквит с ягодной пропиткой и миндальным ванильным кремом со",
    quantity: 1,
    price: 160,
    type: "мини",
  },
  {
    id: 61,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053538.png",
    title: "мини - торт «кофе миндаль»",
    body: "тонкие шоколадные медовые коржи. в сочетании с кофейным сметанным",
    quantity: 1,
    price: 140,
    type: "мини",
  },
  {
    id: 62,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053585.png",
    title: "мини - торт «лесной орех».",
    body: "шоколадный бисквит, пропитанный сахарным сиропом. в сочетании со",
    quantity: 1,
    price: 160,
    type: "мини",
  },
  {
    id: 63,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053600.png",
    title: "мини - торт «медово-яблочный»",
    body: "тонкие медовые коржи. в сочетании с карамельным сметанным кремом,",
    quantity: 1,
    price: 140,
    type: "мини",
  },
  {
    id: 64,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053638.png",
    title: "мини - торт «рафаэлло»",
    body: "воздушный бисквит, пропитанный молочным сиропом. с прослойкой из",
    quantity: 1,
    price: 170,
    type: "мини",
  },
  {
    id: 65,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681727115.",
    title: "мини - торт «тирамису»",
    body: "легкий спонч бисквит с кофейной пропиткой. с начинкой ванильном и",
    quantity: 1,
    price: 140,
    type: "мини",
  },
  {
    id: 66,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672062341.png",
    title: "мини - торт «шоколадно — банановый»",
    body: "шоколадный бисквит, банан намелака, крем 'шатильи', орео и шоколадный",
    quantity: 1,
    price: 190,
    type: "мини",
  },
  {
    id: 67,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1673529365.png",
    title: "сафия мини - торт оформленный",
    body: "классический шифоновый бисквит с вишневым кремом с вишней, банановым",
    quantity: 1,
    price: 300,
    type: "мини",
  },
  {
    id: 68,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053706.png",
    title: "смородина торт",
    body: "смородиновый мини - торт. шоколадные бисквиты, пропитанные",
    quantity: 1,
    price: 140,
    type: "мини",
  },
  {
    id: 69,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058331.png",
    title: "вишнёво - яблочный пирог",
    body: "песочное тесто и нежная начинка из свежих яблок и вишни. пирог рассчитан",
    quantity: 1,
    price: 190,
    type: "бигпироги",
  },
  {
    id: 70,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058356.png",
    title: "вишнёвый пирог",
    body: "песочное тесто и нежная начинка из свежей вишни. пирог рассчитан на 16-18",
    quantity: 1,
    price: 220,
    type: "бигпироги",
  },
  {
    id: 71,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1673253217.png",
    title: "лимонная мозайка пирог",
    body: "песочное тесто и нежная начинка из свежих лимонов и яблок. пирог",
    quantity: 1,
    price: 160,
    type: "бигпироги",
  },
  {
    id: 72,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693219613.png",
    title: "мишка пирог",
    body: "пирог «мишка» - песочное тесто, начинка из кураги и грецких орехов.",
    quantity: 1,
    price: 240,
    type: "бигпироги",
  },
  {
    id: 73,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672059667.png",
    title: "творожная мозайка пирог",
    body: "песочное тесто и нежная начинка из свежего творога. пирог рассчитан на 16-",
    quantity: 1,
    price: 170,
    type: "бигпироги",
  },
  {
    id: 74,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687346570.",
    title: "творожник пирог",
    body: "песочное тесто и нежная начинка из свежего творога. пирог рассчитан на 16-",
    quantity: 1,
    price: 170,
    type: "бигпироги",
  },
  {
    id: 75,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687346661.",
    title: "яблочный пирог",
    body: "песочное тесто, нежная яблочная начинка. пирог рассчитан на 16-18",
    quantity: 1,
    price: 160,
    type: "бигпироги",
  },
  {
    id: 76,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687346863.",
    title: "вишнёвый пирог круглый",
    body: "песочное тесто, вишневая начинка. пирог рассчитан на 6 - 8 персон.",
    quantity: 1,
    price: 100,
    type: "кругпироги",
  },
  {
    id: 77,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672053862.png",
    title: "малиново - фруктовый пирог",
    body: "песочное тесто, сметанная начинка и малиновая заливка. пирог рассчитан на",
    quantity: 1,
    price: 100,
    type: "кругпироги",
  },
  {
    id: 78,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054082.png",
    title: "фисташковый пирог",
    body: "песочное фисташковое тесто, кокосовый крем, малиновое конфи из",
    quantity: 1,
    price: 140,
    type: "кругпироги",
  },
  {
    id: 79,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054148.png",
    title: "шарлотка",
    body: "кекс со свежими яблоками, пропитанный медовым сиропом.",
    quantity: 1,
    price: 38,
    type: "кругпироги",
  },
  {
    id: 80,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693807164.png",
    title: "баноффе эклер",
    body: "заварное (эклер) тесто, арахисовый хрустиланд, мягкая карамель, банан",
    quantity: 1,
    price: 21,
    type: "эклеры",
  },
  {
    id: 81,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690627954.png",
    title: "буше",
    body: "бисквитное печенье, ванильный крем, шоколад. цена указана за 1 кг.",
    quantity: 1,
    price: 110,
    type: "эклеры",
  },
  {
    id: 82,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672906683.png",
    title: "маленький эклер весовой",
    body: "заварное тесто, масляный крем. цена указана за 1 кг. примерное количество в",
    quantity: 1,
    price: 86,
    type: "эклеры",
  },
  {
    id: 83,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690628145.png",
    title: "мини эклеры цветные",
    body: "заварное тесто, сливочно - сгущенный крем. цена указана за 1 кг. примерное",
    quantity: 1,
    price: 140,
    type: "эклеры",
  },
  {
    id: 84,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693807239.png",
    title: "парист брест эклер",
    body: "заварное (эклер) тесто, пекан пралине, карамелизованный пекан, фундучное",
    quantity: 1,
    price: 21,
    type: "эклеры",
  },
  {
    id: 85,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693807420.png",
    title: "рафаэлло эклер",
    body: "заварное (эклер) тесто, кокосовый крем, вафельный хрустиланд. оформлен",
    quantity: 1,
    price: 21,
    type: "эклеры",
  },
  {
    id: 86,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693807472.png",
    title: "тирамису эклер",
    body: "заварное (эклер) тесто, кофейный заварной крем, печенье савоярди,",
    quantity: 1,
    price: 21,
    type: "эклеры",
  },
  {
    id: 83,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672906667.png",
    title: "шоколадный эклер палочки весовой",
    body: "заварное тесто, крем с горьким шоколадом. примерное количество в 1",
    quantity: 1,
    price: 100,
    type: "эклеры",
  },
  {
    id: 84,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1669992159.png",
    title: "блэк форест тарталетка",
    body: "шоколадное песочное тесто, ванильный 'шантильи', молочный 'шантильи' ",
    quantity: 1,
    price: 20,
    type: "тарталетки",
  },
  {
    id: 85,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672831927.png",
    title: "большая тарталетка",
    body: "песочное ореховое тесто с начинкой из шоколадного ганаша и взбитых сливок.",
    quantity: 1,
    price: 80,
    type: "тарталетки",
  },
  {
    id: 86,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672831949.png",
    title: "вольтер мини",
    body: "песочно - миндальное тесто с начинкой из грецкого ореха, миндаля, кешью,",
    quantity: 1,
    price: 60,
    type: "тарталетки",
  },
  {
    id: 87,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672831969.png",
    title: "мини тарталетка",
    body: "песочное ореховое тесто с начинкой из шоколадного ганаша и взбитых сливок.",
    quantity: 1,
    price: 55,
    type: "тарталетки",
  },
  {
    id: 88,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681737651.",
    title: "тропический тарт",
    body: "кокосовый бисквит, с кремами маракуя и кокоса. оформлен шоколадным",
    quantity: 1,
    price: 24,
    type: "тарталетки",
  },
  {
    id: 89,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672831985.png",
    title: "шоколадная мини тарталетка",
    body: "шоколадное песочное тесто с шоколадным молочным ганашом и",
    quantity: 1,
    price: 65,
    type: "тарталетки",
  },
  {
    id: 90,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672915607.png",
    title: "макаронс",
    body: "миндальное тесто с разными начинками (фисташки, малина, маракуйя, шоколад)",
    quantity: 1,
    price: 80,
    type: "макаронсы",
  },
  {
    id: 91,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672827534.png",
    title: "макаронс в коробке, большой",
    body: "миндальное тесто с разными начинками (фисташки, малина, маракуйя, шоколад)",
    quantity: 1,
    price: 96,
    type: "макаронсы",
  },
  {
    id: 92,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672827702.png",
    title: "макаронс в коробке, маленький",
    body: "миндальное тесто с разными начинками (фисташки, малина, маракуйя, шоколад)",
    quantity: 1,
    price: 48,
    type: "макаронсы",
  },
  {
    id: 93,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693223239.png",
    title: "бакинская пахлава",
    body: "",
    quantity: 1,
    price: 42,
    type: "печенья",
  },
  {
    id: 94,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1693208071.png",
    title: "баунти мини печенье сет",
    body: "",
    quantity: 1,
    price: 15,
    type: "печенья",
  },
  {
    id: 95,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1688018469.",
    title: "баунти сет 0,3",
    body: "",
    quantity: 1,
    price: 35,
    type: "печенья",
  },
  {
    id: 96,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687254971.",
    title: "бискотти сет 0,3",
    body: "",
    quantity: 1,
    price: 23,
    type: "печенья",
  },
  {
    id: 97,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687254947.",
    title: "ванильная сердечка сет",
    body: "",
    quantity: 1,
    price: 20,
    type: "печенья",
  },
  {
    id: 98,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687255119.",
    title: "звезда печенье сет 0,25",
    body: "",
    quantity: 1,
    price: 17,
    type: "печенья",
  },
  {
    id: 99,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687255150.",
    title: "звезда печенье сет 0,5",
    body: "",
    quantity: 1,
    price: 33,
    type: "печенья",
  },
  {
    id: 100,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677239978.png",
    title: "классический бискотти",
    body: "",
    quantity: 1,
    price: 40,
    type: "печенья",
  },
  {
    id: 101,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677240001.png",
    title: "кофе бискотти",
    body: "",
    quantity: 1,
    price: 55,
    type: "печенья",
  },
  {
    id: 102,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687255182.",
    title: "кукес сет 0,3",
    body: "",
    quantity: 1,
    price: 18,
    type: "печенья",
  },
  {
    id: 103,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1687255292.",
    title: "кунжут сет 0,3",
    body: "",
    quantity: 1,
    price: 25,
    type: "печенья",
  },
  {
    id: 104,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1675248248.png",
    title: "булочка с вишней",
    body: "сдобное тесто начинка из вишни",
    quantity: 1,
    price: 80,
    type: "сдоба",
  },
  {
    id: 105,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1675248281.png",
    title: "булочка с маком",
    body: "сдобное тесто , начинка из мака",
    quantity: 1,
    price: 70,
    type: "сдоба",
  },
  {
    id: 106,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1675248300.png",
    title: "булочка с орехом",
    body: "сдобное тесто начинка из грецкого ореха",
    quantity: 1,
    price: 80,
    type: "сдоба",
  },
  {
    id: 107,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681728176.",
    title: "булочка с сосиской",
    body: "сдобное тесто, канадская сосиска",
    quantity: 1,
    price: 90,
    type: "сдоба",
  },
  {
    id: 108,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1689858843.png",
    title: "апельсиновый кекс new",
    body: "апельсиновый кекс состоит из нежного апельсинового кекса в сочетании с",
    quantity: 1,
    price: 70,
    type: "кексы",
  },
  {
    id: 109,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1689858872.png",
    title: "вишневый кекс new",
    body: "шоколадный вишневый кекс состоит из шоколадного и ванильного теста в",
    quantity: 1,
    price: 70,
    type: "кексы",
  },
  {
    id: 110,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690628813.png",
    title: "яблочный кекс new",
    body: "яблочный кекс состоит из нежного кекса с корицей, карамелизованными",
    quantity: 1,
    price: 70,
    type: "кексы",
  },
  {
    id: 111,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1678878453.png",
    title: "леденцы",
    body: "",
    quantity: 1,
    price: 90,
    type: "чак",
  },
  {
    id: 112,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1690628745.png",
    title: "мармелад сет",
    body: "",
    quantity: 1,
    price: 21,
    type: "чак",
  },
  {
    id: 113,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238588.png",
    title: "мёд липовый",
    body: "",
    quantity: 1,
    price: 80,
    type: "чак",
  },
  {
    id: 114,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238631.png",
    title: "мороженое в баночке",
    body: "",
    quantity: 1,
    price: 16,
    type: "чак",
  },
  {
    id: 115,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672828304.png",
    title: "муравейник",
    body: "песочное тесто, медово-карамельный крем, вареная сгущёнка в упаковке - 6",
    quantity: 1,
    price: 40,
    type: "чак",
  },
  {
    id: 116,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238538.png",
    title: "орешки (упаковка)",
    body: "песочное тесто, вареная сгущенка, грецкий орех. в упаковке - 10 штук.",
    quantity: 1,
    price: 40,
    type: "чак",
  },
  {
    id: 117,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672307183.png",
    title: "турецкий чак - чак сет",
    body: "песочное тесто, крем из сливочного масла и вареной сгущенки с",
    quantity: 1,
    price: 30,
    type: "чак",
  },
  {
    id: 118,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058130.png",
    title: "вишенка пп торт",
    body: "пп торт 'вишенка' – состоит из миндального бисквита с черным тмином",
    quantity: 1,
    price: 180,
    type: "ппторты",
  },
  {
    id: 119,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058171.png",
    title: "кофе фундук пп торт",
    body: "пп торт 'кофе фундук' – состоит из фундучного бисквита с кофейной",
    quantity: 1,
    price: 180,
    type: "ппторты",
  },
  {
    id: 120,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058200.png",
    title: "лесные ягоды пп торт",
    body: "пп торт 'лесные ягоды' – состоит из ягодного бисквита с чаем каркаде и",
    quantity: 1,
    price: 200,
    type: "ппторты",
  },
  {
    id: 121,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672058238.png",
    title: "матча лимон пп торт",
    body: "пп торт 'матча лимон' – состоит из миндального бисквита с японским чаем",
    quantity: 1,
    price: 200,
    type: "ппторты",
  },
  {
    id: 122,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054298.png",
    title: "сникерс пп мини - торт",
    body: "сникерс пп мини - торт состоит из шоколадного бисквита, пропитанного",
    quantity: 1,
    price: 220,
    type: "ппторты",
  },
  {
    id: 123,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054329.png",
    title: "фисташковый пп мини - торт",
    body: "пп фисташковый мини - торт состоит из фисташкового бисквита,",
    quantity: 1,
    price: 220,
    type: "ппторты",
  },
  {
    id: 124,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054351.png",
    title: "фруктовый пп торт мини",
    body: "пп фруктовый мини - торт состоит из классического белого бисквита,",
    quantity: 1,
    price: 180,
    type: "ппторты",
  },
  {
    id: 125,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672054369.png",
    title: "шоколадно - вишнёвый пп мини - торт",
    body: "шоколадно -вишневый пп мини - торт с вишней состоит из шоколадного",
    quantity: 1,
    price: 190,
    type: "ппторты",
  },
  {
    id: 126,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672916988.png",
    title: "малиновое пп пирожное",
    body: "легкое малиновое пирожное состоит из бисквита на основе смеси из",
    quantity: 1,
    price: 22,
    type: "пппирожные",
  },
  {
    id: 127,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1682567514.",
    title: "карамельный брауни",
    body: "пп медовое пирожное состоит из тонких медовых коржей на основе",
    quantity: 1,
    price: 23,
    type: "пппирожные",
  },
  {
    id: 128,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672917040.png",
    title: "медовое пирожное пп",
    body: "пп медовое пирожное состоит из тонких медовых коржей на основе",
    quantity: 1,
    price: 23,
    type: "пппирожные",
  },
  {
    id: 129,
    img: "https://safiabakery.uz/uploads/products/thumbs/33_1649511152.jpeg",
    title: "наполеон пп пирожное",
    body: "пп «наполеон» пирожное состоит из песочного теста на основе смеси из",
    quantity: 1,
    price: 25,
    type: "пппирожные",
  },
  {
    id: 130,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672917281.png",
    title: "пп батончик класический",
    body: "состав: курага сушеная, овсяные хлопья, ягоды годжи, арахисовая паста",
    quantity: 1,
    price: 15,
    type: "пппирожные",
  },
  {
    id: 131,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672917063.png",
    title: "пп пирожное 'матча лимон'",
    body: "пп пирожное 'матча лимон' – состоит из миндального бисквита с японским",
    quantity: 1,
    price: 28,
    type: "пппирожные",
  },
  {
    id: 132,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672917913.png",
    title: "пп пирожное картошка",
    body: "классическое пирожное картошка состоит из бисквита, на основе смеси из",
    quantity: 1,
    price: 80,
    type: "пппирожные",
  },
  {
    id: 133,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1672916909.png",
    title: "пп пирожное лесная ягода",
    body: "пп пирожное 'лесная ягода' – состоит из ягодного бисквита с чаем каркаде и",
    quantity: 1,
    price: 29,
    type: "пппирожные",
  },
  {
    id: 134,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238802.png",
    title: "вареники с вишней",
    body: "мука, творог, вишня, соль, сливочное масло, яйцо в упаковке - 30 штук",
    quantity: 1,
    price: 29,
    type: "полуфабрикаты",
  },
  {
    id: 135,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238862.png",
    title: "вареники с картошкой",
    body: "мука, картошка, лук, соль, перец, сливочное масло, яйцо в упаковке - 30",
    quantity: 1,
    price: 19,
    type: "полуфабрикаты",
  },
  {
    id: 136,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681727804.",
    title: "котлета говяжья",
    body: "фарш из говядины, лук, специи (без консервантов) в упаковке - 5 штук. цена",
    quantity: 1,
    price: 80,
    type: "полуфабрикаты",
  },
  {
    id: 137,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677238939.png",
    title: "котлеты по-киевски",
    body: "куриное филе, сливочное масло, укроп, соль, перец, панировочные сухарики.",
    quantity: 1,
    price: 36,
    type: "полуфабрикаты",
  },
  {
    id: 138,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677239011.png",
    title: "нагетсы (12 шт)",
    body: "куриное филе, сливочное масло, соль, перец, панировочные сухарики,",
    quantity: 1,
    price: 23,
    type: "полуфабрикаты",
  },
  {
    id: 139,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1681727725.",
    title: "пельмени говяжьи",
    body: "тесто, фарш из говядины, лук, специи (без консервантов) вес: 400 гр.",
    quantity: 1,
    price: 32,
    type: "полуфабрикаты",
  },
  {
    id: 140,
    img: "https://safiabakery.uz/uploads/products/thumbs/33_1641298552.png",
    title: "доставка аниматорами",
    body: "вы только представьте, что тортик вам доставит тот самый герой из",
    quantity: 1,
    price: 150,
    type: "доставка",
  },
  {
    id: 141,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677590655.jpg",
    title: "апельсиновый fresh (safia)",
    body: "",
    quantity: 1,
    price: 39,
    type: "cоки",
  },
  {
    id: 142,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677590641.jpg",
    title: "морковно-яблочный fresh",
    body: "",
    quantity: 1,
    price: 20,
    type: "cоки",
  },
  {
    id: 143,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666076972.jpg",
    title: "морковный fresh (safia)",
    body: "",
    quantity: 1,
    price: 15,
    type: "cоки",
  },
  {
    id: 144,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677673118.jpg",
    title: "яблочный fresh (safia)",
    body: "",
    quantity: 1,
    price: 23,
    type: "cоки",
  },
  {
    id: 145,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666077200.jpg",
    title: "анор смузи",
    body: "",
    quantity: 1,
    price: 30,
    type: "смузи",
  },
  {
    id: 146,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666077143.jpg",
    title: "киви банан смузи",
    body: "",
    quantity: 1,
    price: 30,
    type: "смузи",
  },
  {
    id: 147,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666077260.jpg",
    title: "экзотический смузи",
    body: "",
    quantity: 1,
    price: 30,
    type: "смузи",
  },
  {
    id: 148,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666077329.jpg",
    title: "ягодный смузи",
    body: "",
    quantity: 1,
    price: 30,
    type: "смузи",
  },
  {
    id: 149,
    img: "https://safiabakery.uz/uploads/products/thumbs/no-photo.jpg",
    title: "банановый милкшейк",
    body: "",
    quantity: 1,
    price: 30,
    type: "милкшейки",
  },
  {
    id: 150,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677734689.jpg",
    title: "ванильный милкшейк",
    body: "",
    quantity: 1,
    price: 30,
    type: "милкшейки",
  },
  {
    id: 151,
    img: "https://safiabakery.uz/uploads/products/thumbs/no-photo.jpg",
    title: "шоколадный милкшейк",
    body: "",
    quantity: 1,
    price: 30,
    type: "милкшейки",
  },
  {
    id: 152,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666159102.jpg",
    title: "ягодный милкшейк",
    body: "",
    quantity: 1,
    price: 30,
    type: "милкшейки",
  },
  {
    id: 153,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666077372.jpg",
    title: "карамельный фраппе",
    body: "",
    quantity: 1,
    price: 16,
    type: "фраппе",
  },
  {
    id: 154,
    img: "https://safiabakery.uz/uploads/products/thumbs/161_1666079162.jpg",
    title: "шоколадный фраппе",
    body: "",
    quantity: 1,
    price: 21,
    type: "фраппе",
  },
  {
    id: 155,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677680345.jpg",
    title: "зелёный айс-ти",
    body: "",
    quantity: 1,
    price: 20,
    type: "лимонады",
  },
  {
    id: 156,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677734476.jpg",
    title: "лесная ягода лимонад",
    body: "",
    quantity: 1,
    price: 21,
    type: "лимонады",
  },
  {
    id: 157,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677734488.jpg",
    title: "тархун апельсин лимонад",
    body: "",
    quantity: 1,
    price: 21,
    type: "лимонады",
  },
  {
    id: 158,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677680290.jpg",
    title: "фруктовый айс-ти",
    body: "",
    quantity: 1,
    price: 20,
    type: "лимонады",
  },
  {
    id: 159,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677734589.jpg",
    title: "цитрусовый лимонад",
    body: "",
    quantity: 1,
    price: 20,
    type: "лимонады",
  },
  {
    id: 160,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677680315.jpg",
    title: "чёрный айс-ти",
    body: "",
    quantity: 1,
    price: 20,
    type: "лимонады",
  },
  {
    id: 161,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691486705.jpg",
    title: "borjomi",
    body: "",
    quantity: 1,
    price: 17,
    type: "напитки",
  },
  {
    id: 162,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691485351.png",
    title: "borjomi баночка",
    body: "",
    quantity: 1,
    price: 11,
    type: "напитки",
  },
  {
    id: 163,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691484183.jpg",
    title: "coca cola 0,5",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 164,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691483849.png",
    title: "coca cola баночная",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 165,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691484308.png",
    title: "fanta 0,5",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 166,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691483943.png",
    title: "fanta баночная",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 167,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691485926.png",
    title: "pepsi баночная",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 168,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691483958.png",
    title: "red bull",
    body: "",
    quantity: 1,
    price: 24,
    type: "напитки",
  },
  {
    id: 169,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691483879.png",
    title: "sprite 0,5",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 170,
    img: "https://safiabakery.uz/uploads/products/thumbs/80_1691483899.jpg",
    title: "sprite баночный",
    body: "",
    quantity: 1,
    price: 80,
    type: "напитки",
  },
  {
    id: 171,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677593524.jpg",
    title: "вода chortoq 0.33",
    body: "",
    quantity: 1,
    price: 10,
    type: "напитки",
  },
  {
    id: 172,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677593538.jpg",
    title: "вода chortoq 0.5",
    body: "",
    quantity: 1,
    price: 12,
    type: "напитки",
  },
  {
    id: 173,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677593712.jpg",
    title: "вода б/г",
    body: "",
    quantity: 1,
    price: 30,
    type: "напитки",
  },
  {
    id: 174,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677593723.png",
    title: "вода с/г",
    body: "",
    quantity: 1,
    price: 30,
    type: "напитки",
  },
  {
    id: 175,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677594040.jpg",
    title: "сок 1 л",
    body: "",
    quantity: 1,
    price: 17,
    type: "напитки",
  },
  {
    id: 176,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677931923.jpg",
    title: "американо (safia)",
    body: "",
    quantity: 1,
    price: 14,
    type: "кофе",
  },
  {
    id: 177,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677931936.jpg",
    title: "американо айс (safia)",
    body: "",
    quantity: 1,
    price: 15,
    type: "кофе",
  },
  {
    id: 178,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677589918.jpg",
    title: "двойной американо (safia)",
    body: "",
    quantity: 1,
    price: 16,
    type: "кофе",
  },
  {
    id: 179,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677931968.jpg",
    title: "двойной капучино (safia)",
    body: "",
    quantity: 1,
    price: 22,
    type: "кофе",
  },
  {
    id: 180,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677595656.jpg",
    title: "двойной эспрессо (safia)",
    body: "",
    quantity: 1,
    price: 16,
    type: "кофе",
  },
  {
    id: 181,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677931953.jpg",
    title: "капучино (safia)",
    body: "",
    quantity: 1,
    price: 16,
    type: "кофе",
  },
  {
    id: 182,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677932046.jpg",
    title: "капучино айс (safia)",
    body: "",
    quantity: 1,
    price: 22,
    type: "кофе",
  },
  {
    id: 183,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677590037.jpg",
    title: "кофе раф (safia)",
    body: "",
    quantity: 1,
    price: 24,
    type: "кофе",
  },
  {
    id: 184,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677595710.jpg",
    title: "латте (safia)",
    body: "",
    quantity: 1,
    price: 17,
    type: "кофе",
  },
  {
    id: 185,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677595748.jpg",
    title: "латте айс (safia)",
    body: "",
    quantity: 1,
    price: 19,
    type: "кофе",
  },
  {
    id: 186,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677675411.jpg",
    title: "фраппучино (safia)",
    body: "",
    quantity: 1,
    price: 28,
    type: "кофе",
  },
  {
    id: 187,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677590168.jpg",
    title: "эспрессо (safia)",
    body: "",
    quantity: 1,
    price: 12,
    type: "кофе",
  },
  {
    id: 188,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677589479.jpg",
    title: "имбирно-апельсиновый авторский чай (safia)",
    body: "",
    quantity: 1,
    price: 30,
    type: "чаи",
  },
  {
    id: 189,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677672936.jpg",
    title: "имбирный авторский чай (safia)",
    body: "",
    quantity: 1,
    price: 24,
    type: "чаи",
  },
  {
    id: 190,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677672910.jpg",
    title: "марокканский авторский чай (safia)",
    body: "",
    quantity: 1,
    price: 24,
    type: "чаи",
  },
  {
    id: 191,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677589633.jpg",
    title: "успокаивающий авторский чай (safia)",
    body: "",
    quantity: 1,
    price: 19,
    type: "чаи",
  },
  {
    id: 192,
    img: "https://safiabakery.uz/uploads/products/thumbs/171_1677675367.jpg",
    title: "ягодный авторский чай (safia)",
    body: "",
    quantity: 1,
    price: 24,
    type: "чаи",
  },
];